[package]
name = "tensor_blas_repeat"
version = "0.1.2"
edition = "2021"

[package.metadata.morflow]
action = "repeat"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
core_types = { path = "../../../core_types" }

[[package.metadata.morflow.plugins]]
name = "openblas"
version = "^0.1.0"

[dev-dependencies]
openblas-plugin = { package = "morflow-plugin-openblas", path = "../../../plugins/openblas" }
