[package]
publish = false
name = "morflow-jni"
version = "0.2.6"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "morflow_jni"

[dependencies]
core_types = { package = "morflow-core-types", version = "0.4.2", path = "../../core_types" }
morflow = { package = "morflow", version = "0.2.6", path = "../../pipeline" }
jni = { version = "0.21", default-features = false }
abi_stable = "0.11"
