[package]
name = "morflow"
version = "0.2.6"
edition = "2021"
rust-version = "1.89"
description = "Data Processing & Tensor Transformation Engine"
license = "MIT"
repository = "https://github.com/JiraPit/Morflow"
readme = "../README.md"

[[bin]]
name = "morflow"
path = "src/main.rs"

[dependencies]
core_types = { package = "morflow-core-types", version = "0.4.2", path = "../core_types" }
parser = { package = "morflow-parser", version = "0.2.6", path = "../parser" }
libloading = "0.8"
abi_stable = "0.11"
rayon = "1.10"
clap = { version = "4.5", features = ["derive"] }
ureq = { version = "2.12", default-features = false, features = ["tls", "native-tls"] }
dirs = "6.0"
rich_rust = { version = "0.2.3", features = ["markdown"] }
ariadne = "0.5"
chumsky = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
semver = "1"
tempfile = "3"
