[package]
name = "image_opencv_morphology"
version = "0.1.2"
edition = "2021"

[package.metadata.morflow]
action = "morphology"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
core_types = { path = "../../../core_types" }

[[package.metadata.morflow.plugins]]
name = "opencv-bridge"
version = "^0.1.0"
