[package]
publish = false
name = "morflow-plugin-opencv-bridge"
version = "0.1.2"
edition = "2021"

[lib]
name = "morflow_opencv_bridge"
crate-type = ["cdylib"]

[package.metadata.morflow]
plugin = "opencv-bridge"

[dependencies]
opencv = { version = "0.101", default-features = false, features = ["imgproc"] }

[build-dependencies]
pkg-config = "0.3"
