[package]
publish = false
name = "morflow-plugin-openblas"
version = "0.1.1"
edition = "2021"
autotests = false

[lib]
name = "morflow_openblas_plugin"
crate-type = ["cdylib", "rlib"]

[package.metadata.morflow]
plugin = "openblas"

[dependencies]
core_types = { package = "morflow-core-types", version = "0.4.2", path = "../../core_types" }
libloading = "0.8"

[dev-dependencies]
basic-matmul = { package = "matmul", path = "../../actions/linalg_basics/matmul" }
