[package]
publish = false
name = "image_opencv_sharpen"
version = "0.1.2"
edition = "2021"

[package.metadata.morflow]
action = "sharpen"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
core_types = { package = "morflow-core-types", version = "0.4.2", path = "../../../core_types" }

[[package.metadata.morflow.plugins]]
name = "opencv-bridge"
version = "^0.1.0"
