[package]
name = "morflow-parser"
version = "0.2.6"
edition = "2021"
description = "Parser for Morflow declarative data processing pipelines"
license = "MIT"
repository = "https://github.com/JiraPit/Morflow"

[lib]
name = "parser"

[dependencies]
chumsky = "0.9"
serde = { version = "1.0", features = ["derive"] }
